apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/lreh/my-app-deploy.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lreh/my-app-deploy.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
