apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-app
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: dev
                - env: staging
          - git:
              repoURL: https://github.com/lreh/my-app-deploy.git
              revision: HEAD
              files:
                - path: apps/*.yaml
  template:
    metadata:
      name: '{{env}}-{{metadata.name}}'
    spec:
      project: default
      source:
        repoURL: '{{spec.source.repoURL}}'
        targetRevision: '{{spec.source.targetRevision}}'
        path: '{{spec.source.path}}'
        {{- if spec.source.helm }}
        helm:
          valueFiles:
            - values.yaml
            - values-{{env}}.yaml
        {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
