apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: m-time-service
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            version: HEAD
#          - env: staging
#            version: HEAD
  template:
    metadata:
      name: '{{env}}-m-time-service'
    spec:
      project: default
      source:
        repoURL: https://github.com/Lreh/m-time-service.git
        targetRevision: '{{version}}'
        path: charts/java-app
        helm:
          valueFiles:
            - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}-m-time-service'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
