apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lreh/m-time-service.git
    targetRevision: HEAD
    path: charts/java-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
