apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-service
  namespace: argocd
spec:
  project: default
  source:
    # OPTION 2: Point directly to your source code repository
    repoURL: 'https://github.com/Lreh/m-time-service.git'

    # Point to the folder where Chart.yaml exists in your source repo
    path: charts/time-service

    # Use the HEAD (latest) branch, or specify 'main'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
