apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: time-service
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            version: HEAD
          - env: staging
            version: 1.0.39
  template:
    metadata:
      name: '{{env}}-time-service'
    spec:
      project: default
      source:
        repoURL: https://github.com/Lreh/m-time-service.git
        targetRevision: HEAD
        path: charts/java-app
        helm:
          valueFiles:
            - values-{{env}}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{env}}-time-service'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
